insert into Categories (Name) VALUES ('Groccesies')
insert into Categories (Name) VALUES ('Services')
insert into Categories (Name) VALUES ('Games')
insert into Categories (Name) VALUES ('Fuel')
insert into Categories (Name) VALUES ('Car')
insert into Categories (Name) VALUES ('Householding')
insert into Categories (Name) VALUES ('Medicine')
insert into Categories (Name) VALUES ('Money Send')
insert into Categories (Name) VALUES ('Sport')
insert into Categories (Name) VALUES ('Cafes')
insert into Categories (Name) VALUES ('Transport')
insert into Categories (Name) VALUES ('Museums')
insert into Categories (Name) VALUES ('Others')